package flexGSTIMGUIs;

import channel_package.Channel;
import channel_package.DoubleChannel;
import channel_package.TxtUtil;
import com.fazecast.jSerialComm.SerialPort;
import com.fazecast.jSerialComm.SerialPortDataListener;
import com.fazecast.jSerialComm.SerialPortEvent;
import java.io.PrintWriter;

/**
 * This sub-GUI is instantiated by the MainWindow GUI. Used to update COMM port settings.
 * @author elee1
 */
public class ConnectWindow extends javax.swing.JFrame {
    
    private MainWindow mainWin;
    private SerialPort chosenPort;

   /**
    * Construct ConnectWindow GUI object. MainWindow GUI object is passed
    * as an argument so that we can send information to it. 
    * @param m the main MainWindow
    */
    public ConnectWindow(MainWindow m) {        
        initComponents();
        
        this.mainWin = m;
        this.chosenPort = m.getChosenPort();
        
        updateSelectCOMM();
        updateButtons();
    }
    
    /**
     * Populates the selectCOMM JComboBox with COMM port options
     */
    private void updateSelectCOMM() {
	SerialPort[] portNames = SerialPort.getCommPorts();
	for(int i = 0; i < portNames.length; i++) {
            selectCOMM.addItem(portNames[i].getSystemPortName());
        }     
    }
    
    /**
     * Updates connect JButton with proper text and enables/disables accordingly
     */
    private void updateButtons() {
        if(chosenPort!=null && chosenPort.openPort()) {//check if already connected
            connect.setText("Disconnect");
            selectCOMM.setSelectedItem(chosenPort.getSystemPortName());
            selectCOMM.setEnabled(false);
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectCOMM = new javax.swing.JComboBox<>();
        connect = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Connection");

        connect.setText("Connect");
        connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectActionPerformed(evt);
            }
        });

        jLabel1.setText("Select COMM port");

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(connect, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectCOMM, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(selectCOMM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(connect)
                    .addComponent(cancel))
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Called when user pressed "Connect" button. Attempts to connect (or disconnect)
     * to selected COMM port.
     * @param evt 
     */
    private void connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectActionPerformed

        if(connect.getText().equals("Connect")) {
            // attempt to connect to the serial port
            chosenPort = SerialPort.getCommPort(selectCOMM.getSelectedItem().toString());
            chosenPort.setComPortTimeouts(SerialPort.TIMEOUT_SCANNER, 0, 0);
            
            if(chosenPort.openPort()) {
                //update chosenPort in MainWindow
                mainWin.setChosenPort(chosenPort);
                
                //delete this window
                this.dispose();
            }
        } else {
            //update chosenPort in MainWindow
            mainWin.setChosenPort(null);
            
            // disconnect from the serial port
            chosenPort.closePort();
            selectCOMM.setEnabled(true);
            connect.setText("Connect");
        }
    }//GEN-LAST:event_connectActionPerformed

    /**
     * Called when user presses "Cancel" button. Disposes of GUI window
     * without saving any changes.
     * @param evt 
     */
    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JButton connect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> selectCOMM;
    // End of variables declaration//GEN-END:variables
}
